# Generated by Django 4.1.3 on 2022-12-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFamiliares', '0002_remove_familiar_presencia_familiar_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechadecampeon', models.DateField()),
                ('ultimorival', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Familiar',
            new_name='Jugadores',
        ),
    ]
